FROM golang:1.24.6 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build asyncq worker
RUN go build -o backend-worker ./cmd/worker/main.go

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/backend-worker .
COPY --from=builder /app/.env .

CMD ["./backend-worker"]
