name: Pre-release on push to main

on:
  push:
    branches:
      - main

jobs:
  create_prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create or update rolling pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "pre-release" \
            --draft \
            --prerelease \
            --title "Pre-release (rolling)" \
            --notes "Latest commit: $GITHUB_SHA" \
            || gh release edit "pre-release" \
              --draft \
              --prerelease \
              --title "Pre-release (rolling)" \
              --notes "Updated for commit $GITHUB_SHA"
